# Docs
# - https://docs.fastlane.tools
# - https://docs.fastlane.tools/actions
# - https://docs.fastlane.tools/actions/increment_build_number
# - https://docs.fastlane.tools/plugins/available-plugins
# - https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane
#
# Helpful examples
# - https://circleci.com/docs/2.0/deploying-ios/
# - http://bytepace.com/blog/fastlane

default_platform(:ios)

platform :ios do

  desc 'Firebase: Distribute beta'
  lane :firebase_distribute_beta do
    increment_build_number(
      build_number: Time.now.to_i
    )
    build_app(
      scheme: 'Stacks',
      archive_path: './build/Stacks.xcarchive',
      export_method: 'development',
      output_directory: './build/Stacks',
      # TODO Try replacing com.apple.developer.icloud-container-environment in Stacks.entitlements with this
      # - https://github.com/fastlane/fastlane/issues/12044
      export_options: {iCloudContainerEnvironment: 'Development'}
    )
    firebase_app_distribution(
      app: '1:649977413874:ios:e5c13f240795a955a4106b',
      testers: 'jdanbrown@gmail.com',
      release_notes: 'Dummy release notes',
      firebase_cli_path: '/usr/local/bin/firebase',
      ipa_path: './build/Stacks/Stacks.ipa'
    )
  end

end
